### PR TITLE
Deal with alumni/team

### LINKED ISSUE #32: team and alumni folder location
From @Nasafato:  "The question is — where is the best place to put the alumni and team folders? I personally dislike having them in the root directory, and feel that they belong in the about page folder."

Following the guidelines [here](http://ben.balter.com/2015/02/20/jekyll-collections/#when-to-use-a-post-a-page-or-a-collection), it seems these should be in collections (since they're not really date/time ordered).

### LINKED ISSUE #71: Move alumni to team and add id
It's simpler to consider alumni and current lab members as just members of the team (so we'll add them all to the team folder).  We'll need a "status" attribute to filter by e.g.,
```
{{ site.categories.team | where:"status","current" }}
```
 for the team page.  

This way we can reference team members (current and alumni) from other pages of the site via something like:
```
{% assign member = site.categories.team | where:"id",author.id %}
```
thereby reducing duplication.  

Haven't tested the filters...hope they work

### LINKED ISSUE #75: Various posts should refer to author by id
Continuation of #74 

@chrisnatali

### PR DESCRIPTION
**Pull request by vr2262**
Closes #71
Closes #32
Closes #75

### CODE REVIEW

**Comment by chrisnatali** [comment]
getting there.  not seeing the lab member pages on this commit (because team is a collection?).  We should also wrap the member.full_name with an href to the member.url in about/index.md

**Comment by vr2262** [comment]
So, in summary:

- Team member post URLs look like `/team/Member-Name/`.
- `alumni/` and `team/` have merged to become the `_team/` collection. The distinction is now `status`, either `current` or `former`.
- Every team member has an `id` that posts can reference as `author`.
- The `_includes/author_name.html` include can pick out an author's `full_name` from the `id`. (See a8b236ce56af37154a6640a19eda5fa1bf425978).
- A number of stragglers lost in the migration are now back in the fold.

Should be good to merge @chrisnatali

**Comment by vr2262** [comment]
The next step (another branch and PR) is to deal with #72.

**Comment by chrisnatali** [comment]
Great.  Created #76 as a leftover.

**Pull request merged**
