### PR TITLE
no listings message, updated projects

### LINKED ISSUE #142: Update Jobs Page
Update current projects, fix indent?
 
http://qsel.columbia.edu/jobs/

### PR DESCRIPTION
**Pull request by mkc1**
fixes #142 

please double-check project descriptions; tried to keep them concise

### CODE REVIEW

**Comment by vr2262** [comment]
Seems good to me.

@jmbott ?

**Comment by jmbott** [comment]
Looks good, maybe highlight current tools like you highlight current projects. Dokomo & Network Planner.

**Comment by mkc1** [comment]
added tools.. I don't see any blog posts/tagged articles for Network Planner?

**Comment by jmbott** [comment]
Could do a publication, 
http://127.0.0.1:4000/assets/uploads/blog/2013/09/EnergyForSustainableDevelopment-ElectrificationPlanningInGhana-KemausuorEtAl.pdf

might make things less standard tho

**Comment by vr2262** [comment]
I think [http://qsel.columbia.edu/tags/#Energy Planning](http://qsel.columbia.edu/tags/#Energy Planning) is the tag for Network Planner... maybe

**Pull request closed without merging**
