### PR TITLE
Issue #22 prose

### PR DESCRIPTION
**Pull request by ssilwal**

### CODE REVIEW

**Comment by ssilwal** [comment]
for some reason, this branch still isn't showing up on prose, can we delete it and move to "prose-fix-maybe"

**Comment by vr2262** [comment]
@ssilwal I'll take a look once I get into the lab.

Do you want to delete this branch or merge it into master...?

Also, was there a merge conflict before you merged master?

**Comment by ssilwal** [comment]
don't think there was a conflict,
and just delete it, and try editing prose with another branch that will be displayed on the prose site.

**Comment by vr2262** [comment]
@ssilwal I see what the problem is. It's pretty funny

Prose uses the branch name in the URL (http://prose.io/#SEL-Columbia/SEL-Columbia.github.io/tree/issue-#22-prose-merge) but the `#` in the branch name means that the URL is actually http://prose.io/#SEL-Columbia/SEL-Columbia.github.io/tree/issue-

We should just avoid putting `#` in the branch names... the number itself is fine. I'll make a new branch.

**Comment by vr2262** [comment]
@ssilwal Yep, that was it: http://prose.io/#SEL-Columbia/SEL-Columbia.github.io/tree/issue-22-prose

**Comment by vr2262** [comment]
@ssilwal looking through the commits for this branch, why don't you start over in a branch off of master called `ssilwal-issue-22-prose`? I'll close this pull request.

**Pull request closed without merging**
