### PR TITLE
adding hernan and member template

### LINKED ISSUE #73: Add Hernan to team

### PR DESCRIPTION
**Pull request by chrisnatali**
Closes #73 and added member template, consistent with updated [wiki page](https://github.com/SEL-Columbia/SEL-Columbia.github.io/wiki/Manage-Lab-Members)

### CODE REVIEW

**Comment by vr2262** [comment]
@chrisnatali I'm not sure whether the template needs to be there, but sure, why not?

I made a few minor changes. If they look reasonable to you, I'll merge this.

**Comment by chrisnatali** [comment]
Looks good.  Thanks.

**Comment by chrisnatali** [comment]
agreed, template's not necessary, but it made documenting adding a member in the wiki less arbitrary (than say copying some random member's markdown file).

**Comment by vr2262** [comment]
@chrisnatali delete the branch at your discretion

**Pull request merged**
